name: Nodejs app Clinics Server

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  IMAGE_NAME: clinics-api
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and tag Docker image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:${GITHUB_SHA} .
          docker tag $DOCKERHUB_USERNAME/$IMAGE_NAME:${GITHUB_SHA} $DOCKERHUB_USERNAME/$IMAGE_NAME:latest

      - name: Log in to Docker Hub
        run: docker login --username $DOCKERHUB_USERNAME --password $DOCKERHUB_PASSWORD

      - name: Push Docker image
        run: docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:${GITHUB_SHA} && docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:latest
      - name: Success Message
        run: echo "Successfully build the docker image and pushed to docker hub"
